services:
  # Backend Service 1: Constructor Connect
  constructor-backend:
    image: python:3.10-slim
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - "./backend/engineer&constructor_connect_backend:/app"
    command: sh -c "pip install --no-cache-dir -r requirements.txt && flask run --host=0.0.0.0 --port=5000"

  # Backend Service 2: Blueprint Generator
  blueprint-backend:
    image: python:3.10-slim
    working_dir: /app
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./backend/blueprint-generator:/app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && flask run --host=0.0.0.0 --port=5002"

  # Backend Service 3: Marketplace
  marketplace-backend:
    image: python:3.10-slim
    working_dir: /app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=marketPlace.py
    volumes:
      - ./backend/marketPlace:/app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && flask run --host=0.0.0.0 --port=5001"
