// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMIfKaXW9mt9VmuBVHuwXzmyiwmeEB0Ws',
    appId: '1:286258998209:web:a1aff1bfdcf2261eeb5d40',
    messagingSenderId: '286258998209',
    projectId: 'archisri-system',
    authDomain: 'archisri-system.firebaseapp.com',
    storageBucket: 'archisri-system.firebasestorage.app',
    databaseURL: 'https://archisri-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    measurementId: 'G-QK3K86H958',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB07msx9D6tNXS9RIOcVUER35hG03reFn0',
    appId: '1:286258998209:android:7532263c704f86d4eb5d40',
    messagingSenderId: '286258998209',
    projectId: 'archisri-system',
    storageBucket: 'archisri-system.firebasestorage.app',
    databaseURL: 'https://archisri-system-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs0k-YYYpaT8RYeskh86ccX2uNONJra0Y',
    appId: '1:286258998209:ios:28dcfd7c4a571f1aeb5d40',
    messagingSenderId: '286258998209',
    projectId: 'archisri-system',
    storageBucket: 'archisri-system.firebasestorage.app',
    databaseURL: 'https://archisri-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    androidClientId: '286258998209-191atsp9auc0a1k96pg7kfvnk2bqma6p.apps.googleusercontent.com',
    iosClientId: '286258998209-pn15s9kp0d0pk9ombbjd8urpdbm5e6k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.archisri1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs0k-YYYpaT8RYeskh86ccX2uNONJra0Y',
    appId: '1:286258998209:ios:28dcfd7c4a571f1aeb5d40',
    messagingSenderId: '286258998209',
    projectId: 'archisri-system',
    storageBucket: 'archisri-system.firebasestorage.app',
    databaseURL: 'https://archisri-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    androidClientId: '286258998209-191atsp9auc0a1k96pg7kfvnk2bqma6p.apps.googleusercontent.com',
    iosClientId: '286258998209-pn15s9kp0d0pk9ombbjd8urpdbm5e6k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.archisri1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMIfKaXW9mt9VmuBVHuwXzmyiwmeEB0Ws',
    appId: '1:286258998209:web:f3fc60e7a0f89419eb5d40',
    messagingSenderId: '286258998209',
    projectId: 'archisri-system',
    authDomain: 'archisri-system.firebaseapp.com',
    storageBucket: 'archisri-system.firebasestorage.app',
    databaseURL: 'https://archisri-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    measurementId: 'G-DMW7ZLT2QF',
  );
}
